---
title: "study1 preprocessing"
output: 
  html_document:
      toc: true
      toc_float: true
      toc_depth: 3
      number_sections: true
date: "2024-12-10"
author: anonymous
---


```{r}
knit_by_pkgdown <- !is.null(knitr::opts_chunk$get("fig.retina"))
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # TRUE is usually better for debugging
  echo = TRUE  # show R code
)

library(pacman)
pacman::p_load(tidyverse, here, codebook)
ggplot2::theme_set(ggplot2::theme_bw())
sessionInfo()

```

# Read data

```{r}
base_path <- here("code", "study1")
data_path <- paste0(base_path, "/snapshots_study1_preprocessing_analysis/data_processed_step1.csv")
d <- read_csv(data_path) %>% 
      mutate(
        subject_id = as.factor(subject_id),
        trial_type = as.factor(trial_type),
        trial_type_order = as.factor(trial_type_order),
        itemA = as.factor(itemA),
        itemB = as.factor(itemB),
        categoryA = as.factor(categoryA),
        categoryB = as.factor(categoryB)
      )
```

```{r, echo = FALSE}
var_label(d) <- list(
  subject_id =  "Subject ids for all 50 subjects", 
  trial_type = "Factor showing the two experimental conditions: Causal Task vs Sorting Task",
  trial_type_order = "Factor showing the two experimental orders, Causal Task first or Sorting Task first",
  trial_index = "Index indicating the page of the trial. Subjects had about 15 pages of trials",
  question_index = "Index of the questions subjects had. Each subject had about 229 questions including attention checks",
  original_trial_index = "Pre-transformed trial index before running pre-processing script",
  original_question_index = "Pre-transformed question index before running pre-processing script",
  response = "Slider rating for the causal pairs. Values range from 0 to 100 with 0 being `definitely not` and 100 being `definitely yes`",
  itemA = "First item in the pairing in the Causal Task. This is the cause",
  itemB = "second item in the pairing in the Causal Task. This is the effect",
  categoryA = "A priori category (or domain) of itemA, or the first item",
  categoryB = "A priori category (or domain) of itemB, or the second item",
  attention_check_id = "value showing id of the attention check question, it was one of four ids",
  correct = "Indicates if attention check question was correct based on predefined answer",
  x = "x coordinate of item in the sorting canvas for the Sorting Task",
  y = "y coordinate of item in the sorting canvas for the Sorting Task",
  item = "item ID in Sorting Task"
)

metadata(d)$name <- "Step 1 Processed data showing raw x y coordinates of Sorted items, and raw Causal ratings"
metadata(d)$description <- "This dataset is generated by the pre-processing script and is a cleaned up version of the raw data. It contains x and y coordinates of the items in the sorting task, response values for the causal task, and a few extra columns"

```


```{r}
codebook::codebook(d)
```



