---
title: "study1 preprocessing"
output: 
  html_document:
      toc: true
      toc_float: true
      toc_depth: 3
      number_sections: true
date: "2024-12-10"
author: anonymous
---


```{r}
knit_by_pkgdown <- !is.null(knitr::opts_chunk$get("fig.retina"))
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # TRUE is usually better for debugging
  echo = TRUE  # show R code
)

library(pacman)
pacman::p_load(tidyverse, here, codebook)
ggplot2::theme_set(ggplot2::theme_bw())
sessionInfo()

```

# Read data

```{r, echo = FALSE}
base_path <- here("code", "study1", "snapshots_study1_preprocessing_analysis")
data_path <- paste0(base_path, "/data_model_predictions.csv")
d <- read_csv(data_path)

```


```{r, echo = FALSE}
var_label(d) <- list(
  itemA = "First item among item pairs in the Causal Task. This is the cause.",
  itemB = "second item among item pairs in the Causal Task. This is the effect.",
  `theor1_Mind-Body-Action` = "Similarity value assigned to each item pairing for the Mind, Body, Action model. For example, a similarity of 0 for `hear something` and `see something` indicated the model predicts these two items are very similar, since they are both predicted to be in the Mind category",
  `theor2_PerCog-OdActSpAct-BodyStimBodynoStim` = "Similarity value assigned to each item pairing for the Fine grained Mind, Body Action model. For example, a similarity of 0 for `hear something` and `see something` indicated the model predicts these two items are very similar, since they are both predicted to be in the Perceptual Items category",
  `theor3_Physical-Ethereal` = "Similarity value assigned to each item pairing for the Physical and Psychological/Ethereal model. For example, a similarity of 0 for `hear something` and `see something` indicated the model predicts these two items are very similar, since they are both predicted to be in the Ethereal or psychological items category",
  `theor4_cosine_similarity` = "Similarity value assigned to each item pairing for USE word embeddings model"
)

metadata(d)$name <- "Model predictions for the 4 models"
metadata(d)$description <- "Data frame describing the model predictions of the 4 models. This data frame is generated by the study1_preprocessing.Rmd script. The values in the dataset represent similarity scores with 0 being very similar and 1 being very disimilar. These values will be used to build model RDMs for comparison with the empirical RDMs from the Causal Task and Sorting Task"

```


```{r}
codebook::codebook(d)
```


