---
title: "study1 preprocessing"
output: 
  html_document:
      toc: true
      toc_float: true
      toc_depth: 3
      number_sections: true
date: "2024-12-10"
author: anonymous
---


```{r}
knit_by_pkgdown <- !is.null(knitr::opts_chunk$get("fig.retina"))
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # TRUE is usually better for debugging
  echo = TRUE  # show R code
)

library(pacman)
pacman::p_load(tidyverse, here, codebook)
ggplot2::theme_set(ggplot2::theme_bw())
sessionInfo()

```

# Read data

```{r, echo = FALSE}
base_path <- here("code", "study1")
data_path <- paste0(base_path, "/snapshots_study1_final_analysis/freesort_minus_causals.csv")
d <- read_csv(data_path)
```


```{r, echo = FALSE}
var_label(d) <- list(
        itemA = "The first item among item pairs in the study 1 Causal Task, which acts as the `cause` item",
        itemB = "The first item among item pairs in the study 1 Causal Task, which acts as the `effect` item",
        domain_itemA = "The domain of the first item in the pair, per RSA results of study 1" ,
        domain_itemB = "The domain of the second item in the pair, per RSA results of study 1",
        mean_causal_distance = "The mean causal distance between item A and item B",
        mean_freesort_distance = "The mean freesort distance between item A and item B",
        freesort_minus_causal = "The difference between the freesort distance and the causal distance"
)

metadata(d)$name <- "Dataset containing freesort minus causal scores from Study 1, to be used for selecting items for Study 2"
metadata(d)$description <- "This data set was generated by the study1_analysis.Rmd script. It contains item-pair-averaged freesort and causal distances. That is, this data was geneated after averaging the ratings for each item pair across subjects. There are 210 rows, corresponding to the 210 possible item pairs"

```


```{r}
codebook::codebook(d)
```


